# Generated by Django 4.1.5 on 2023-06-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('correoCliente', models.CharField(max_length=50, unique=True, verbose_name='Correo')),
                ('contrasenaCliente', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('runCliente', models.CharField(max_length=12, unique=True, verbose_name='Run')),
                ('nombresCliente', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apPaternoCliente', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apMaternoCliente', models.CharField(max_length=50, verbose_name='Apellido Materno ')),
                ('direccionCliente', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefonoCliente', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Marca')),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('idMecanico', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Mecanico')),
                ('runMecanico', models.CharField(max_length=12, unique=True, verbose_name='Run Mecanico')),
                ('nombresMecanico', models.CharField(max_length=100, verbose_name='Nombres Mecanico')),
                ('apPaternoMecanico', models.CharField(max_length=50, verbose_name='Ap Paterno Mecanico')),
                ('apMaternoMecanico', models.CharField(max_length=50, verbose_name='Ap Materno Mecanico')),
                ('direccionMecanico', models.CharField(max_length=100, verbose_name='Direccion Mecanico')),
                ('telefonoMecanico', models.IntegerField(verbose_name='Telefono Mecanico')),
                ('correoMecanico', models.CharField(max_length=50, verbose_name='Correo Mecanico')),
                ('sueldoMecanico', models.IntegerField(verbose_name='Sueldo Mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Servicio')),
                ('nombreServicio', models.CharField(max_length=50, verbose_name='Nombre Servicio')),
                ('precioServicio', models.IntegerField(verbose_name='Precio Servicio')),
                ('descripcionServicio', models.CharField(max_length=200, verbose_name='Descripcion Servicio')),
                ('imagenServicio', models.ImageField(default='core/img/logobueno.png', upload_to='core/img/', verbose_name='Imagen del servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('username', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('direccion', models.CharField(max_length=80, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca vehiculo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Modelo')),
                ('nombreModelo', models.CharField(max_length=50, verbose_name='Nombre Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
        ),
    ]
