# Generated by Django 4.1.5 on 2023-06-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagenServicio',
            field=models.ImageField(default='core/static/core/img/Alan.jpg', upload_to='core/static/core/img', verbose_name='Imagen del servicio'),
        ),
    ]
