# Generated by Django 4.1.5 on 2023-06-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicio_imagenservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagenServicio',
            field=models.ImageField(upload_to='servicios', verbose_name='Imagen del servicio'),
        ),
    ]
