# Generated by Django 4.1.5 on 2023-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicio_imagenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='default', max_length=50, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='correo@correo.cl', max_length=254, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
    ]
