# Generated by Django 4.2.2 on 2023-06-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_apellido_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcionServicio',
            field=models.CharField(max_length=500, verbose_name='Descripcion Servicio'),
        ),
    ]
