# Generated by Django 4.1.5 on 2023-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Rut'),
        ),
    ]
