# Generated by Django 4.1.5 on 2023-06-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_mensaje_pasaporte_alter_mensaje_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='pasaporte',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='descripcionMecanico',
            field=models.CharField(default='descripcion ejemplo', max_length=500, verbose_name='Descripcion de mecanico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mecanico',
            name='imagenMecanico',
            field=models.ImageField(default='core/img/logobueno.png', upload_to='mecanicos', verbose_name='Imagen del mecanico'),
        ),
        migrations.AddField(
            model_name='mecanico',
            name='trabajosRealizados',
            field=models.IntegerField(default=1, verbose_name='Trabajos realizados'),
            preserve_default=False,
        ),
    ]
