# Generated by Django 4.1.5 on 2023-07-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_mensaje_pasaporte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
